export const schema = `
CREATE TABLE IF NOT EXISTS ACCOUNT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    accountName TEXT DEFAULT NULL,
    balance INTEGER DEFAULT NULL,
    isDeleted INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS CATEGORY (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    categoryName TEXT DEFAULT NULL,
    transactionType TEXT DEFAULT NULL,
    isDeleted INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TXN (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  dateStr TEXT DEFAULT NULL,
  accountId INTEGER DEFAULT NULL,
  categoryId INTEGER DEFAULT NULL,
  toAccountId INTEGER DEFAULT NULL,
  amount INTEGER DEFAULT NULL,
  note TEXT DEFAULT NULL,
  monthYear TEXT DEFAULT NULL
);

INSERT INTO ACCOUNT (id, accountName, balance, isDeleted)
SELECT 1, 'Savings', 0, 0
FROM ACCOUNT WHERE NOT EXISTS (SELECT id FROM ACCOUNT WHERE id = 1);

INSERT INTO ACCOUNT (id, accountName, balance, isDeleted)
SELECT 2, 'Credit Card', 0, 0
FROM ACCOUNT WHERE NOT EXISTS (SELECT id FROM ACCOUNT WHERE id = 2);

INSERT INTO ACCOUNT (id, accountName, balance, isDeleted)
SELECT 3, 'Cash', 0, 0
FROM ACCOUNT WHERE NOT EXISTS (SELECT id FROM ACCOUNT WHERE id = 3);

INSERT INTO CATEGORY (id, categoryName, transactionType)
SELECT 1, 'Food', 'DEBIT'
FROM CATEGORY WHERE NOT EXISTS (SELECT id FROM CATEGORY WHERE id = 1);

INSERT INTO CATEGORY (id, categoryName, transactionType)
SELECT 2, 'Transport', 'DEBIT'
FROM CATEGORY WHERE NOT EXISTS (SELECT id FROM CATEGORY WHERE id = 2);

INSERT INTO CATEGORY (id, categoryName, transactionType)
SELECT 3, 'Medicine', 'DEBIT'
FROM CATEGORY WHERE NOT EXISTS (SELECT id FROM CATEGORY WHERE id = 3);

INSERT INTO CATEGORY (id, categoryName, transactionType)
SELECT 4, 'Salary', 'CREDIT'
FROM CATEGORY WHERE NOT EXISTS (SELECT id FROM CATEGORY WHERE id = 4);

INSERT INTO CATEGORY (id, categoryName, transactionType)
SELECT 5, 'Refund', 'CREDIT'
FROM CATEGORY WHERE NOT EXISTS (SELECT id FROM CATEGORY WHERE id = 5);
`